Update 16KB page size kernel to builds 11987101
git log --first-parent -100 --oneline --no-decorate 0643e9e3d6b1..dd9c02ccfe27:
dd9c02ccfe27 ANDROID: 16K: Avoid mmap lock assertions for padding VMAs
2c5e07cea30f ANDROID: ABI: update symbol list for honor
9842b4145bac ANDROID: GKI: net: add vendor hook for network quality estimation
df9e426fab63 ANDROID: abi_gki_aarch64_qcom: update abi symbol list
93fd111566be ANDROID: GKI: Update symbol list for Amlogic
d072b31467da UPSTREAM: filemap: add helper mapping_max_folio_size()
15fc1b760fa5 ANDROID: android: Add symbols to debug_symbols driver
42eb612b2599 ANDROID: Enable Rust Binder Module
cb0bef6d8ee8 ANDROID: rust_binder: Switch Rust Binder to GKI Module
b511e79bc5ff ANDROID: Only warn on long symbols
4a571c32cb48 ANDROID: Re-enable Rust symbol export
9b771fcf576c ANDROID: ABI: Update symbol list for Exynos SoC.
7ee86e5b15bf ANDROID: vendor_hooks: Add hooks for util-update related functions
e484bff0c491 ANDROID: ABI: update symbol list for honor
047f3eded89e ANDROID: mm: create vendor hooks for memory reclaim
3ebe062ee3a6 ANDROID: ABI: update symbol list for honor
d61134668c2d ANDROID: Allow vendor modules perform operationson on memleak detect
666cbbfe5c56 ANDROID: 2024/06/14 KMI update
d039dba18144 ANDROID: Enable CONFIG_STACKTRACE_BUILD_ID=y
066872d13d0c FROMLIST: BACKPORT: THP shattering: the reverse of collapsing
c1ff6dcf209e FROMLIST: BACKPORT: THP zones: the use cases of policy zones
ace063af70fc ANDROID: ABI: mm: swap: reserve cluster according to mount option.
216c128a8cc7 FROMLIST: BACKPORT: mm: swap: mTHP allocate swap entries from nonfull list
6b195c7c13a6 FROMLIST: BACKPORT: mm: swap: swap cluster switch to double link list
6806bc0f5df0 BACKPORT: FROMGIT: dm: optimize flushes
3a1e448e38a6 ANDROID: vendor_hooks: add inode as param to android_rvh_ctl_dirty_rate
d5e8c5722508 ANDROID: vendor_hooks: modify vendor hook for page protect
6400b81a2f34 ANDROID: GKI: Add cgroup ABI padding
a005717641cf ANDROID: GKI: Add ANDROID_BACKPORT_RESERVE_ARRAY
9f5900a1e7b7 FROMLIST: PM: EM: Add min/max available performance state limits
7f9b34a3c3c8 UPSTREAM: soc: samsung: exynos-asv: Update Energy Model after adjusting voltage
af4d57d97c83 UPSTREAM: PM: EM: Add em_dev_update_chip_binning()
bb91f5e8934b UPSTREAM: PM: EM: Refactor em_adjust_new_capacity()
95af804c1f4c UPSTREAM: OPP: OF: Export dev_opp_pm_calc_power() for usage from EM
a0eff1404e76 UPSTREAM: PM: EM: Force device drivers to provide power in uW
13446441fb27 UPSTREAM: PM: EM: Fix nr_states warnings in static checks
dabff50e1ac7 UPSTREAM: Documentation: EM: Update with runtime modification design
6e77f2b0e8c1 UPSTREAM: PM: EM: Add em_dev_compute_costs()
3a759c566571 UPSTREAM: PM: EM: Remove old table
ce0c15c7e7ec UPSTREAM: PM: EM: Change debugfs configuration to use runtime EM table data
ae5953e9d24e UPSTREAM: drivers/thermal/devfreq_cooling: Use new Energy Model interface
8b5af51ee005 UPSTREAM: drivers/thermal/cpufreq_cooling: Use new Energy Model interface
5a5d1292dbcf UPSTREAM: powercap/dtpm_devfreq: Use new Energy Model interface to get table
94aa16fdac62 UPSTREAM: powercap/dtpm_cpu: Use new Energy Model interface to get table
0c04804e7ddc BACKPORT: PM: EM: Optimize em_cpu_energy() and remove division
3a386e98188d UPSTREAM: PM: EM: Support late CPUs booting and capacity adjustment
73ee214aebda BACKPORT: PM: EM: Add performance field to struct em_perf_state and optimize
9c018a05c8d7 UPSTREAM: PM: EM: Add em_perf_state_from_pd() to get performance states table
dddecb12400d UPSTREAM: PM: EM: Introduce em_dev_update_perf_domain() for EM updates
4c863dbb8014 UPSTREAM: PM: EM: Add functions for memory allocations for new EM tables
028e73d4599b BACKPORT: PM: EM: Use runtime modified EM for CPUs energy estimation in EAS
93f31a5fdf8f UPSTREAM: PM: EM: Introduce runtime modifiable table
7bdec8994445 UPSTREAM: PM: EM: Split the allocation and initialization of the EM table
eecf92b331e2 UPSTREAM: PM: EM: Check if the get_cost() callback is present in em_compute_costs()
393a17f96747 UPSTREAM: PM: EM: Introduce em_compute_costs()
79b4068e2395 UPSTREAM: PM: EM: Find first CPU active while updating OPP efficiency
6ade7c7f189a UPSTREAM: PM: EM: Extend em_cpufreq_update_efficiencies() argument list
b6ff1ddb40b1 UPSTREAM: PM: EM: Add missing newline for the message log
617e6b5fbfa0 UPSTREAM: PM: EM: Refactor em_pd_get_efficient_state() to be more flexible
88930467e9bf ANDROID: dma-buf: align flag types for uncached heap
31662623dfa6 ANDROID: dma-buf: align fd_flags and heap_flags with uapi
30d2da22a338 BACKPORT: FROMLIST: dma-buf/heaps: Correct the types of fd_flags and heap_flags
1ad8e57df73e BACKPORT: FROMGIT: dma-buf: align fd_flags and heap_flags with dma_heap_allocation_data
b1e9dead3e8c ANDROID: GKI: reserve one u64 field in mm_struct for future backports
26f9f515d1b9 ANDROID: usb: Add vendor hook for usb suspend and resume
3b153dabfcd0 ANDROID: KVM: arm64: Don't double account relinquished page
a3ef4deeb834 FROMGIT: KVM: arm64: FFA: Release hyp rx buffer
84a1dab4614e UPSTREAM: af_unix: Update unix_sk(sk)->oob_skb under sk_receive_queue lock.
ea5125eb60a8 ANDROID: GKI: add symbols for rtmutex and mm
8bc9708bc9d2 ANDROID: mm: swapon: Introduce mthp_reserve_* flags
15f36aa87a3a FROMGIT: mm: set pte writable while pte_soft_dirty() is true in do_swap_page()
ea2ca3594aed FROMGIT: BACKPORT: mm: introduce pmd|pte_needs_soft_dirty_wp helpers for softdirty write-protect
f7eeffbb7dc6 FROMGIT: BACKPORT: mm: swap: reuse exclusive folio directly instead of wp page faults
f9034e21df8a ANDROID: cpufreq: Improve util tracking and add pressure
2dd2a189c633 FROMGIT: BACKPORT: mm: drop the 'anon_' prefix for swap-out mTHP counters
6a2c5a9c6e78 FROMGIT: mm: huge_mm: fix undefined reference to `mthp_stats' for CONFIG_SYSFS=n
20c5972c7619 FROMGIT: mm: arm64: fix the out-of-bounds issue in contpte_clear_young_dirty_ptes
2a51abdebdb6 FROMGIT: BACKPORT: mm: swap: entirely map large folios found in swapcache
46ae25fadf44 UPSTREAM: mm: remove some calls to page_add_new_anon_rmap()
bef1e0682378 FROMGIT: mm: swap: make should_try_to_free_swap() support large-folio
d92f2e398130 FROMGIT: mm: introduce arch_do_swap_page_nr() which allows restore metadata for nr pages
2f425f068c3c FROMGIT: mm: introduce pte_move_swp_offset() helper which can move offset bidirectionally
6508d828b88d FROMGIT: mm: remove the implementation of swap_free() and always use swap_free_nr()
846f70a82fc9 FROMGIT: mm: swap: introduce swap_free_nr() for batched swap_free()
bb616d66d8a9 ANDROID: Delete obsolete 16k_gki.fragment.
30febe1eb202 Revert "Revert "ANDROID: syscall_check: add vendor hook for open..."
f430ba848154 Revert "ANDROID: GKI: net: add vendor hooks for 'struct nf_conn' lifecycle"
c95c8e73af67 Revert "ANDROID: syscall_check: add vendor hook for open syscall"
befe27c52953 ANDROID: GKI: update symbol list file for xiaomi
1ac616c90301 ANDROID: GKI: Update QCOM symbol list
ac0e65d760c5 ANDROID: abi_gki_aarch64_vivo: Update symbol list
91868ca6152c ANDROID: Update symbol list for MTK
af0b7d880ab2 ANDROID: ABI: Update pixel symbol list
d3cf5eb7a429 UPSTREAM: freezer,sched: Clean saved_state when restoring it during thaw
1da401e43075 UPSTREAM: freezer,sched: Do not restore saved_state of a thawed task
bb064dd1e04a ANDROID: Improve module loader checks for GKI symbol protection
9acf2adaf5b7 ANDROID: GKI: update symbol list file for xiaomi
97a274d252f6 FROMGIT: arm64: mte: Make mte_check_tfsr_*() conditional on KASAN instead of MTE
52a033e8980a ANDROID: KVM: arm64: Move init after setting the ops
abd6c25f0d5f ANDROID: KVM: arm64: iommu: Add idmap trace point

Test: treehugger
Bug: 345252092
Bug: 328138888
Bug: 347270344
Bug: 346741763
Signed-off-by: Kalesh Singh <kaleshsingh@google.com>
(cherry picked from https://googleplex-android-review.googlesource.com/q/commit:3f8bf783182ca8851840776b4143dff7e96d987f)
Merged-In: I2a6f08027a467c6a2d123b73dff2b8e45d1fc423
Change-Id: I2a6f08027a467c6a2d123b73dff2b8e45d1fc423